### ISSUE TITLE
Support dynamic scaffolding

### ISSUE THREAD

**Issue by mpccolorado** [MayGo/grails-scaffold-core#2]
It would be great if it bring support for dynamic scaffolding for controllers pointing out which template to use for the controller.

```
class MyController{
     static scaffold = 'backendSrc/pathToTemplateController';
}
```

PS: Always want a plugin like this! It brings much more power to scaffolding!

**Comment by MayGo** [comment]
I don't want plugin to know anything about controllers.
Plugin generates only based on Domain objects.
I would rather implement solution that watches domain classes for changes and regenerates dynamic templates.

Maybe i don't understand the problem you are trying to solve.

**Comment by mpccolorado** [comment]
I was thinking in the same behavior as the default scaffold techniques in grails (you can specify the controllers code with a static scaffold named 'field'), but thinking about it now it makes sense not mixing things (scaffolding and behavior of controllers)
