### ISSUE TITLE
Error running script twice

### ISSUE THREAD

**Issue by mpccolorado** [MayGo/grails-scaffold-core#6]
An exception occurs when I run the script for the second time:

```
No such property: scaffoldCorePluginDir for class: Scaffold
```

I have defined the grails-scaffold-core as an inline plugin.

**Comment by MayGo** [comment]
I have had problems with reloading templates when in inline mode.
Does this problem occur when not in inline mode?

**Comment by mpccolorado** [comment]
No, I just tried with the 

```
compile ":scaffold-core:1.3.0"
```

and it works fine!
