### ISSUE TITLE
Doesn't load templates from a custom plugin

### ISSUE THREAD

**Issue by mpccolorado** [MayGo/grails-scaffold-core#7]
If I create a plugin who depends on the grails-scaffold-core plugin and define some templates on it, those templates are not found when I run the script to generate files from them. As a workaround I have to copy the templates on the desired project.

**Comment by MayGo** [comment]
You have to define DefaultTemplatesLocator bean.
Example:
https://github.com/MayGo/grails-scaffold-angular/blob/master/ScaffoldAngularGrailsPlugin.groovy#L20

2015-05-29 18:21 GMT+03:00 Martín Caballero notifications@github.com:

**Comment by mpccolorado** [comment]
Thanks!
