### ISSUE TITLE
Import on partial template

### ISSUE THREAD

**Issue by mpccolorado** [MayGo/grails-scaffold-core#8]
Any idea on how to import a custom class inside a partial template?

```
<%import myPackage.MyClass%>
```

That line generates an error inside a partial template because it is waiting to get a map instead of another thing.

Thanks!

**Comment by MayGo** [comment]
in partial file you can't import classes because it is not a template file. You have to use fully-qualified class name.
Maybe it is possible to write: 
Class myClass = myPackage.MyClass
def myClassInst = new myClass()
