### ISSUE TITLE
Create binary plugin

### ISSUE THREAD

**Issue by mpccolorado** [MayGo/grails-scaffold-core#9]
Have you tried to create a binary plugin using this plugin?
I tried it without success. It doesn't work.
I created a binary plugin from a plugin using the scaffoldCore but when I try to use the scaffold method from a third plugin it doesn't work.

```
Error executing script Scaffold: grails/plugin/scaffold/core/DefaultTemplatesLocator
```

**Comment by MayGo** [comment]
I havent tried creating binary plugin.

2015-08-03 14:24 GMT+03:00 Martín Caballero notifications@github.com:
